### ISSUE TITLE
Kill a worker

### ISSUE THREAD

**Issue by Fianax** [lubritto/easy_isolate#3]
I have a process that I carry out in a worker that I want to be done infinitely until I change the page.

I had thought about killing the worker so that his loopEvent ends as well.

How do you kill a worker?

**Comment by lubritto** [comment]
Seems okay for your case, you can call ‘worker.dispose()’ to kill the isolate and close the ports. @Fianax

**Comment by Fianax** [comment]
thanks for your help.
